/*
 *  PBcfg.c
 *
 *  Created on: Aug 31, 2024
 *      Author:Zyad Ayman
 */

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION           (1U)
#define PORT_PBCFG_SW_MINOR_VERSION           (0U)
#define PORT_PBCFG_SW_PATCH_VERSION           (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION   (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION   (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION   (3U)


#include "Port.h"


/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif





/* PB structure used with  Init API */
const  Port_ConfigType  Port_PinConfig = {
         PORTA ,  PIN_NO_0,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTA ,  PIN_NO_1,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTA ,  PIN_NO_2,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTA ,  PIN_NO_3,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTA ,  PIN_NO_4,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTA ,  PIN_NO_5,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTA ,  PIN_NO_6,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTA ,  PIN_NO_7,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,

         PORTB ,  PIN_NO_0,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTB ,  PIN_NO_1,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTB ,  PIN_NO_2,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTB ,  PIN_NO_3,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTB ,  PIN_NO_4,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTB ,  PIN_NO_5,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTB ,  PIN_NO_6,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTB ,  PIN_NO_7,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,

         PORTC ,  PIN_NO_0,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTC ,  PIN_NO_1,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTC ,  PIN_NO_2,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTC ,  PIN_NO_3,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTC ,  PIN_NO_4,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTC ,  PIN_NO_5,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTC ,  PIN_NO_6,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTC ,  PIN_NO_7,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,

         PORTD ,  PIN_NO_0,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTD ,  PIN_NO_1,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTD ,  PIN_NO_2,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTD ,  PIN_NO_3,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTD ,  PIN_NO_4,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTD ,  PIN_NO_5,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTD ,  PIN_NO_6,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTD ,  PIN_NO_7,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,

         PORTE ,  PIN_NO_0,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTE ,  PIN_NO_1,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTE ,  PIN_NO_2,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTE ,  PIN_NO_3,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTE ,  PIN_NO_4,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTE ,  PIN_NO_5,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,

         PORTF ,  PIN_NO_0,  PIN_IN, OFF,  PIN_LEVEL_LOW ,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTF ,  PIN_NO_1,  PIN_OUT, OFF,  PIN_LEVEL_LOW,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTF ,  PIN_NO_2,  PIN_IN, OFF,  PIN_LEVEL_LOW,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTF ,  PIN_NO_3,  PIN_IN, OFF,  PIN_LEVEL_LOW,  PIN_MODE_DIO , STD_ON, STD_ON,
         PORTF ,  PIN_NO_4,  PIN_IN, PULL_UP,  PIN_LEVEL_LOW,   PIN_MODE_DIO , STD_ON, STD_ON

};


